try {
    console.log(foo);
}
catch(e) {
    console.log('something went wrong here is more info');
    console.log(e)
}
const a = 1;
console.log(a);
